const config = [
  {
    name: "Chloé Chicky",
    position: ["Comédienne", "clown"],
    cie: [
      "Conservatoire 11e (Paris)",
      "Licence Histoire de l’art",
      "(option Art du spectacle)",
      "Studio Muller (Paris)",
      "Cie la Valise ondulatoire",
      "Cie les sbires sibériens",
      "Cie le Vélo volé",
      "Cie Luce",
    ],
    imageName: "chloe.webp",
  },
  {
    name: "Pauline Laurendeau",
    position: ["Comédienne", "musicienne"],
    cie: [
      "Ecole La scène sur Saône (Lyon)",
      "Master Psychologie clinique",
      "Cie la Connerie Nouvelle",
      "Conférence burlesque",
      "Le bernoute",
    ],
    imageName: "pauline.webp",
  },
  {
    name: "Mathias Minne",
    position: ["Comédien", "réalisateur"],
    cie: [
      "Conservatoire du 11e (Paris)",
      "Cie La boîte à lettres",
      "Films, téléfilms, clips:",
      "Antigone - Ivo Van Hove",
      "Il fait jour ce matin (Film)",
      "Ganjouriho (Festival de Clermont Ferrand, 1er Prix Festival 7e Lune)",
    ],
    demo: "https://vimeo.com/mathiasminne",
    imageName: "mathias.webp",
  },
  {
    name: "Arthur Viadieu",
    position: ["Comédien", "metteur en scène"],
    cie: [
      "Master Biologie Moléculaire",
      "Conservatoire du 11e (Paris)",
      "École Jacques Lecoq",
      "Théâtre Majaz",
      "Cie Luce",
    ],
    imageName: "arthur.webp",
  },
  {
    name: "Roma Blanchard",
    position: ["Comédien", "Drag Queen"],
    cie: [
      "Conservatoire de Genève",
      "Conservatoire de Lyon",
      "Stage avec Krystian Lupa",
      "Collectif Xanadou",
      "Cie Tumulte",
    ],
    imageName: "roma.webp",
  },
  {
    name: "Marie-Line Vergnaux",
    position: ["Comédienne", "Metteuse en scène"],
    cie: [
      "Mise en scène : Quelqu’un pour veiller sur moi",
      "2h14 Mention Spéciale Prix Théâtre 13 2016",
      "Ecole les Enfants Terribles (Paris)",
      "Conservatoire du 11e (Paris)",
      "Licence Art du Spectacle",
      "Cie Bacchus",
      "Cie Luce",
    ],
    imageName: "marie-line.webp",
  },
  {
    name: "Bob Levasseur",
    position: ["Comédien"],
    cie: [
      "Formacion integral de Teatro Corporal Jorge Costa (Buenos Aires)",
      "Téléfilms (TF1, FR2, CANAL PLUS), clips, publicités",
      "Conservatoire du 11e (Paris)",
      "Cie les Mille chandelles",
      "Cie La boîte aux lettres",
      "Studio Alain de Bock",
      "Cie Luce (2h14)",
    ],
    imageName: "bob.webp",
  },
  {
    name: "Anaïs Ancel",
    position: ["Comédienne", "clown"],
    cie: [
      "Electre des bas-fonds Simon Abkarian",
      "Studio Alain de Bock",
      "Cie Les épis noirs",
      "Cie Sans soucis",
      "Cie du Crayon",
      "Thermos",
      "Arzapar",
      "Viva",
    ],
    imageName: "anais.webp",
  },
  {
    name: "Claire Olier",
    position: ["Comédienne", "metteuse en scène"],
    cie: ["Conservatoire du 11e (Paris)", "Cie 5ème acte", "Cie Luce"],
    imageName: "claire.webp",
  },
  {
    name: "Régis Fortino",
    position: ["Comédien", "réalisateur"],
    cie: [],
    imageName: "regis.webp",
  },
  {
    name: "Sarah Calcine",
    position: ["Comédienne", "metteuse en scène"],
    cie: [
      "Manufacture de Lausanne / Compagnie Boule à facettes",
      "On achève bien les oiseaux / Festival Fragments",
      "Mon petit monde porno, de Gabriel Calderón",
      "Talents Cannes Adami / Sacha (série Arte)",
      "National d'Arts Scéniques de Montevideo",
      "Mains d'Oeuvres / Innocence de Dea Loher",
      "Festival in situ de Villeréal",
      "Compagnie COMPLOT (Uruguay)",
    ],
    imageName: "sarah.webp",
  },
  {
    name: "Antoine Mermet",
    position: ["Musicien", "Compositeur"],
    cie: [
      "The Very Big Experimental Toubifri Orchestra",
      "Collectif Dur&Doux / Cie Groupe Fantomas",
      "Bouche Amplifiée / Tiphaine Calmettes",
      "Cie Kopfkino / Cie Connerie Nouvelle",
      "Vocoder / Service Délicat",
      "CHROMB! / Saint Sadrill",
    ],
    imageName: "antoine.webp",
  },
];

export default config;
