const config = [
  {
    name: "Chloé Chicky",
    position: ["Comédienne", "clown"],
    cie: [
      "Licence Histoire de l’art option Art du spectacle",
      "Studio Muller (Paris)",
      "Conservatoire 11e arrondissement (Paris)",
      "Cie le Vélo volé",
      "Cie Luce",
      "Cie la Valise ondulatoire",
      "Cie les sbires sibériens",
    ],
    imageName: "chloe.webp",
  },
  {
    name: "Pauline Laurendeau",
    position: ["Comédienne", "musicienne"],
    cie: [
      "Master Psychologie clinique",
      "Ecole La scène sur Saône (Lyon)",
      "Conférence burlesque",
      "Le bernoute",
      "Cie la Connerie Nouvelle",
    ],
    imageName: "pauline.webp",
  },
  {
    name: "Mathias Minne",
    position: ["Comédien", "réalisateur"],
    cie: [
      "Conservatoire du 11e (Paris)",
      "Cie La boîte à lettres",
      "Antigone Ivo Van Hove",
      "Films, téléfilms, clips",
      "Ganjouriho (Festival de Clermont Ferrand, 1er Prix Festival 7e Lune)",
      "Il fait jour ce matin",
    ],
    demo: "https://vimeo.com/mathiasminne",
    imageName: "mathias.webp",
  },
  {
    name: "Arthur Viadieu",
    position: ["Comédien", "metteur en scène"],
    cie: [
      "Master Biologie Moléculaire",
      "Conservatoire du 11e (Paris)",
      "Ecole Jacques Lecoq",
      "Théâtre Majaz",
      "Cie Luce",
    ],
    imageName: "arthur.webp",
  },
  {
    name: "Roma Blanchard",
    position: ["Comédien", "Drag Queen"],
    cie: [
      " Conservatoire de Genève",
      "Conservatoire de Lyon",
      " Stage avec Krystian Lupa",
      " Cie Tumulte",
      "Collectif Xanadou",
    ],
    imageName: "roma.webp",
  },
  {
    name: "Marie-Line Vergnaux",
    position: ["Comédienne", "Metteuse en scène"],
    cie: [
      "Licence Art du Spectacle",
      "Ecole les Enfants Terribles (Paris)",
      "Conservatoire du 11e (Paris)",
      "Cie Bacchus",
      "Cie Luce",
      "Mise en scène : Quelqu’un pour veiller sur moi",
      "2h14 Mention Spéciale Prix Théâtre 13 2016",
    ],
    imageName: "marie-line.webp",
  },
  {
    name: "Bob Levasseur",
    position: ["Comédien"],
    cie: [
      "Studio Alain de Bock",
      "Formacion integral de Teatro Corporal Jorge Costa (Buenos Aires)",
      "Conservatoire du 11e (Paris)",
      "Cie les Mille chandelles",
      "Cie La boîte aux lettres",
      "Cie Luce (2h14)",
      "Téléfilms (TF1, FR2, CANAL PLUS), clips, publicité",
    ],
    imageName: "bob.webp",
  },
  {
    name: "Anaïs Ancel",
    position: ["Comédienne", "clown"],
    cie: [
      "Studio Alain de Bock",
      "Cie Les épis noirs",
      "Cie du Crayon",
      "Thermos",
      "Arzapar",
      "Cie Sans soucis",
      "Viva",
      "Electre des bas-fonds Simon Abkarian",
    ],
    imageName: "anais.webp",
  },
  {
    name: "Claire Olier",
    position: ["Comédienne", "metteuse en scène"],
    cie: ["Conservatoire du 11e (Paris)", "Cie Luce", "Cie 5ème acte"],
    imageName: "claire.webp",
  },
  {
    name: "Régis Fortino",
    position: ["Comédien", "réalisateur"],
    cie: [],
    imageName: "regis.webp",
  },
  {
    name: "Sarah Calcine",
    position: ["Comédienne", "metteuse en scène"],
    cie: [
      "Manufacture de Lausanne / Compagnie Boule à facettes",
      "On achève bien les oiseaux / Festival Fragments",
      "Mon petit monde porno, de Gabriel Calderón",
      "Compagnie COMPLOT (Uruguay)",
      "National d'Arts Scéniques de Montevideo",
      "Mains d'Oeuvres / Innocence de Dea Loher",
      "Festival in situ de Villeréal",
      "Talents Cannes Adami / Sacha (série Arte)",
    ],
    imageName: "sarah.webp",
  },
  {
    name: "Antoine Mermet",
    position: ["Musicien", "Compositeur"],
    cie: [
      "CHROMB! / Saint Sadrill",
      "Bouche Amplifiée / Tiphaine Calmettes",
      "The Very Big Experimental Toubifri Orchestra",
      "Vocoder / Service Délicat",
      "Collectif Dur&Doux / Cie Groupe Fantomas",
      "Cie Kopfkino / Cie Connerie Nouvelle",
    ],
    imageName: "antoine.webp",
  },
];

export default config;
